"""Initial migration

Revision ID: c59d1eb73cae
Revises: 12c25c293a84
Create Date: 2025-07-14 06:32:35.101878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59d1eb73cae'
down_revision: Union[str, Sequence[str], None] = '12c25c293a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_uuid', sa.String(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('related_agency_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('audit_type_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('special_case_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('analysis_text', sa.Text(), nullable=True),
    sa.Column('hwp_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['audit_type_id'], ['audit_types.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['related_agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['special_case_id'], ['special_cases.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viewer_case_uuid'), 'viewer', ['case_uuid'], unique=True)
    op.create_index(op.f('ix_viewer_id'), 'viewer', ['id'], unique=False)
    op.drop_index(op.f('ix_gamsa_cases_case_uuid'), table_name='gamsa_cases')
    op.drop_index(op.f('ix_gamsa_cases_id'), table_name='gamsa_cases')
    op.drop_table('gamsa_cases')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamsa_cases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('case_uuid', sa.VARCHAR(), nullable=False),
    sa.Column('agency_id', sa.INTEGER(), nullable=False),
    sa.Column('related_agency_id', sa.INTEGER(), nullable=True),
    sa.Column('region_id', sa.INTEGER(), nullable=True),
    sa.Column('audit_type_id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('field_id', sa.INTEGER(), nullable=False),
    sa.Column('special_case_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('result', sa.TEXT(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('original_text', sa.TEXT(), nullable=True),
    sa.Column('analysis_text', sa.TEXT(), nullable=True),
    sa.Column('hwp_path', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['audit_type_id'], ['audit_types.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['related_agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['special_case_id'], ['special_cases.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamsa_cases_id'), 'gamsa_cases', ['id'], unique=False)
    op.create_index(op.f('ix_gamsa_cases_case_uuid'), 'gamsa_cases', ['case_uuid'], unique=1)
    op.drop_index(op.f('ix_viewer_id'), table_name='viewer')
    op.drop_index(op.f('ix_viewer_case_uuid'), table_name='viewer')
    op.drop_table('viewer')
    # ### end Alembic commands ###
